Feature: Audio-Reactive Edge Effects
  As an artist creating AMV-style music video art,
  I want to pair a video of a person with a separate music file and have detected edges
  pulse, warp, and displace in sync with the music,
  So that my visual edge layers are synchronized with the soundtrack for dynamic, beat-driven compositions.

  Background:
    Given the EffectRule system is installed and configured
    And the AudioReactiveEdgeRule is available as a registered rule
    And an input video file is available
    And a separate audio file is provided as input

  # --- Audio File Loading and Analysis ---

  Scenario: Separate audio file is loaded and analyzed before video processing
    Given a video file "dance.mp4" at 30fps
    And a separate audio file "soundtrack.mp3"
    When I run the pipeline with AudioReactiveEdgeRule in the chain
    Then the audio file is loaded and analyzed before frame processing begins
    And beat onsets are detected from the audio file
    And spectral features are computed for each video frame's corresponding audio window
    And the pre-computed audio analysis is available to the rule during frame processing

  Scenario: Audio analysis produces per-frame feature vectors aligned to video frame rate
    Given a video file at 30fps with 300 frames
    And a separate audio file "track.wav" that is 10 seconds long
    When the audio analysis step completes
    Then 300 per-frame audio feature vectors are produced
    And each feature vector includes bass energy, mid energy, high energy, and onset strength
    And feature vectors are time-aligned to their corresponding video frames based on the video's frame rate

  Scenario: Audio analysis handles different audio formats
    Given a video file "dance.mp4"
    And an audio file in MP3 format
    When I run the audio analysis step
    Then the audio is loaded and analyzed successfully
    And per-frame feature vectors are produced

  Scenario: Audio analysis handles different sample rates
    Given a video file "dance.mp4"
    And an audio file at 44100 Hz sample rate
    And another audio file at 48000 Hz sample rate
    When I run the audio analysis step on both
    Then both produce valid per-frame feature vectors
    And the feature vectors are comparable in scale regardless of sample rate

  Scenario: Audio file longer than video is truncated to video duration
    Given a video file with 300 frames at 30fps (10 seconds)
    And a separate audio file that is 30 seconds long
    When I run the pipeline with AudioReactiveEdgeRule
    Then only the first 10 seconds of audio are analyzed
    And the analysis aligns to the 300 video frames

  Scenario: Audio file shorter than video pads remaining frames with silence
    Given a video file with 300 frames at 30fps (10 seconds)
    And a separate audio file that is 5 seconds long
    When I run the pipeline with AudioReactiveEdgeRule
    Then the first 150 frames have audio-reactive displacement based on the music
    And frames 151-300 have zero displacement as if silent
    And a warning indicates the audio file is shorter than the video

  # --- Beat-Driven Edge Pulsing ---

  Scenario: Edges pulse outward on beat onsets
    Given a video file "dance.mp4"
    And a separate audio file with a steady beat at 120 BPM
    And an edge map of a person generated by EdgeDetect
    When I apply AudioReactiveEdgeRule with default settings
    Then edges displace outward from the person's center on each beat onset
    And the displacement is visible as a brief expansion of the silhouette contour
    And the pulse occurs within 1-2 frames of the detected beat onset

  Scenario: Edge displacement magnitude correlates with bass energy
    Given a video file "dance.mp4"
    And a separate audio file that alternates between loud bass hits and quiet passages
    And an edge map of a person
    When I apply AudioReactiveEdgeRule with default settings
    Then edge displacement is larger during loud bass hits
    And edge displacement is smaller or zero during quiet passages
    And the displacement magnitude scales proportionally with bass energy

  Scenario: Strong beat produces larger pulse than weak beat
    Given a video file "dance.mp4"
    And a separate audio file containing both strong downbeats and weak offbeats
    When I apply AudioReactiveEdgeRule with default settings
    Then downbeat frames show larger edge displacement than offbeat frames
    And the ratio of displacement reflects the relative onset strength

  # --- Frequency Band Mapping ---

  Scenario: High-frequency bands affect fine detail edges
    Given a video file "dance.mp4"
    And a separate audio file containing high-frequency content (hi-hats, cymbals)
    And an edge map at detail level 8 with both coarse and fine edges
    When I apply AudioReactiveEdgeRule with default frequency band weights
    Then fine detail edges (hair, fingers, fabric texture) shimmer or oscillate in response to high frequencies
    And coarse structural edges (silhouette, limbs) are less affected by high-frequency content

  Scenario: Low-frequency bands affect coarse structural edges
    Given a video file "dance.mp4"
    And a separate audio file containing strong bass content
    And an edge map at detail level 8
    When I apply AudioReactiveEdgeRule with default frequency band weights
    Then coarse structural edges (silhouette, limb boundaries) displace in response to bass
    And fine detail edges are less affected by low-frequency content

  Scenario: Custom frequency band weights override defaults
    Given a video file "dance.mp4"
    And a separate audio file with a mixed frequency track
    When I apply AudioReactiveEdgeRule with custom band weights: bass 0.2, mid 0.5, high 1.0
    Then edge reactivity is weighted toward high-frequency content
    And fine edge shimmer is more pronounced than bass-driven displacement
    And the behavior differs from default band weights

  # --- Temporal Smoothness and Decay ---

  Scenario: Smooth decay between beats with no hard jumps
    Given a video file "dance.mp4"
    And a separate audio file with beats spaced 0.5 seconds apart
    When I apply AudioReactiveEdgeRule with decay_rate 0.85
    Then edge displacement peaks on each beat onset
    And displacement decays smoothly over subsequent frames until the next beat
    And no consecutive frame pair shows an abrupt jump in displacement

  Scenario: Decay rate is configurable
    Given a video file "dance.mp4"
    And a separate audio file with a steady beat
    When I apply AudioReactiveEdgeRule with decay_rate 0.5
    And I apply AudioReactiveEdgeRule with decay_rate 0.95
    Then the 0.5 decay version returns to baseline quickly after each beat
    And the 0.95 decay version sustains displacement longer between beats
    And both versions show smooth frame-to-frame transitions

  Scenario: Displacement interpolates smoothly during sustained notes
    Given a video file "dance.mp4"
    And a separate audio file with a long sustained bass note over 60 frames
    When I apply AudioReactiveEdgeRule
    Then edge displacement is sustained smoothly for the duration of the note
    And there are no flickering or oscillating artifacts during the sustained section
    And displacement gradually releases as the note fades

  # --- Configuration ---

  Scenario: Configure sensitivity to control overall reactivity
    Given a video file and a separate audio file
    When I apply AudioReactiveEdgeRule with sensitivity 0.3
    And I apply AudioReactiveEdgeRule with sensitivity 1.0
    Then the sensitivity-1.0 version shows larger edge displacements
    And the sensitivity-0.3 version shows subtler edge reactions
    And both versions react to the same beat onsets

  Scenario: Configure displacement scale
    Given a video file and a separate audio file
    When I apply AudioReactiveEdgeRule with displacement_scale 5 pixels
    And I apply AudioReactiveEdgeRule with displacement_scale 20 pixels
    Then maximum edge displacement is approximately 5 pixels in the first case
    And maximum edge displacement is approximately 20 pixels in the second case

  Scenario: Configure frequency band weights
    Given a video file and a separate audio file
    When I apply AudioReactiveEdgeRule with band_weights: {bass: 1.0, mid: 0.5, high: 0.2}
    Then the rule responds most strongly to bass frequencies
    And mid-frequency response is attenuated to half
    And high-frequency response is attenuated to one-fifth

  Scenario: Full configuration via YAML with separate audio file
    Given a YAML configuration containing:
      """
      pipeline:
        input: "dance.mp4"
        audio: "soundtrack.mp3"
        output: "amv_output.mp4"
        rules:
          - name: EdgeDetect
            params:
              algorithm: hed
              detail_level: 6
          - name: AudioReactiveEdgeRule
            params:
              sensitivity: 0.7
              decay_rate: 0.85
              displacement_scale: 15
              band_weights:
                bass: 1.0
                mid: 0.4
                high: 0.8
      """
    When I load and execute the rule chain
    Then the audio file "soundtrack.mp3" is loaded and analyzed separately from the video
    And EdgeDetect runs first producing an edge map
    And AudioReactiveEdgeRule applies audio-driven displacement to those edges
    And all configured parameters are respected

  # --- No Audio File Provided (Graceful Fallback) ---

  Scenario: No audio file provided makes rule a passthrough
    Given a video file "silent_clip.mp4"
    And no separate audio file is provided
    When I apply AudioReactiveEdgeRule
    Then the rule acts as a passthrough producing no edge displacement
    And the output frames are identical to the input frames
    And a warning message indicates no audio file was provided

  Scenario: Silent audio file produces no displacement
    Given a video file "dance.mp4"
    And a separate audio file that is entirely silent
    When I apply AudioReactiveEdgeRule
    Then no beat onsets are detected
    And edge displacement remains at zero for all frames
    And the output frames are identical to the input frames

  # --- Integration with Other Rules ---

  Scenario: AudioReactiveEdgeRule chains after EdgeDetect
    Given a video file and a separate audio file
    And a rule chain configured as [EdgeDetect, AudioReactiveEdgeRule]
    When I run the rule chain
    Then EdgeDetect produces edge maps per frame
    And AudioReactiveEdgeRule receives those edge maps and applies audio-driven displacement
    And the final output shows edges that pulse with the music

  Scenario: AudioReactiveEdgeRule chains with depth compositing
    Given a video file and a separate audio file
    And a rule chain configured as [EdgeDetect, AudioReactiveEdgeRule, DepthComposite]
    When I run the rule chain
    Then edges are detected, displaced by audio, then composited with depth
    And the depth compositing operates on the audio-displaced edges

  # --- Error Handling ---

  Scenario: Corrupted audio file produces clear error
    Given a video file "dance.mp4"
    And a separate audio file that is corrupted and cannot be decoded
    When I attempt to run the pipeline with AudioReactiveEdgeRule
    Then the pipeline returns an error indicating the audio file could not be decoded
    And the error suggests checking the audio file format or running without AudioReactiveEdgeRule

  Scenario: Unsupported audio format produces clear error
    Given a video file "dance.mp4"
    And a separate audio file "track.midi" in an unsupported format
    When I attempt to run the pipeline with AudioReactiveEdgeRule
    Then the pipeline returns an error listing supported audio formats as MP3, WAV, FLAC, AAC, and OGG
    And no frames are processed

  Scenario: Audio file path does not exist produces clear error
    Given a video file "dance.mp4"
    And an audio file path "nonexistent.mp3" that does not exist on disk
    When I attempt to run the pipeline with AudioReactiveEdgeRule
    Then the pipeline returns an error indicating the audio file was not found
    And the error includes the path that was searched
